name: BOOST
on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *" # crontab.guru
jobs:
  stonks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Modify last update
        run: |
          d=`date '+%Y/%m/%dT%H:%M:%SZ'`
          echo $d > TEMP
      - name: Commit changes
        run: |
          git config --local user.email ${{ secrets.MAIL }}
          git config --local user.name ${{ secrets.USERNAME }}
          git add -A
          txt[0] = "Sometimes your mistakes can surprise you"
          txt[1] = "People who say they have nothing to hide almost always do"
          txt[2] = "I don’t particularly like killing people, but I’m very good at it"
          txt[3] = "Once we become predictable, we become vulnerable"
          txt[4] = "You always have a choice, even if it’s between two bad options"
          txt[5] = "The most efficient way to lose in a fight is to act without knowing your enemy"
          txt[6] = "We have free will, and with that comes great responsibility, and sometimes great loss"
          txt[7] = "If they don’t want you to get inside, they ought to build it better"
          txt[8] = "Bad guys always run"
          txt[9] = "Obstacles are only obstacles until you move them out of the way"
          txt[10] = "The problem with trying to be the bad guy is there’s always someone worse"
          txt[11] = "We walk in the dark. Doesn’t mean we have to walk in it alone"
          txt[12] = "When the whole world is watched, filed, indexed, numbered, the only way to disappear is to appear"
          txt[13] = "Not everything that’s broken is meant to be fixed"
          txt[14] = "Maybe there are no good people. Maybe there are only good decisions"
          txt[15] = "No one ever said we were gonna win, but it doesn’t mean you stop fighting"
          txt[16] = "The correct animal for inter-species super soldier is the koala. You would wind up with an army so cute, it couldn’t be attacked"
          txt[17] = "I promised myself if I ever got friends I’d do whatever they said. Really, I’m lucky you found me before a cult did"
          txt[18] = "Indian Monopoly is just like regular Monopoly, but instead of money you use rupees, instead of building hotels you build call centers, and when you pick up a chance card there’s a chance you die of dysentery. And just FYI, that was racist"
          txt[19] = "Love is not a sprint, it’s a marathon, a relentless pursuit that only ends when she falls into your arms (or hits you with the pepper spray)"
          txt[20] = "That is a good point. But I didn’t marry you for good points. I married you to blindly support me no matter how ridiculous I’m being"
          txt[21] = "If it’s ‘creepy’ to use the Internet, military satellites, and robot aircraft to find a house full of gorgeous young models so I can drop in on them unexpected, then fine, I’m creepy"
          txt[22] = "Not really a great outfit for work, unless something opens up in the hookers and whores department"
          txt[23] = "I know the real reason you never made progress with that idea. You thought of it September 22nd, 2007. Two days later, Penny moved in and so much blood rushed to your genitals, your brain became a ghost town"
          txt[24] = "I often forget other people have limitations. It’s so sad"
          txt[25] = "The only way she’d be able to make a contribution to science is if they resume sending chimps into space"
          txt[26] = "Trying is the first step toward failure"
          txt[27] = "I’m sure wherever my Dad is, he’s looking down on us. He’s not dead, just very condescending"
          txt[28] = "Good parenting means investing in your child’s future, which is why I bought my son… a confectionery store. Is that not clear?"
          txt[29] = "Sheldon: Leonard, I am detecting a strange odor. Leonard: Sheldon, I know, I smell it too. Sheldon: Describe it. Leonard: Oh, I can’t describe it. Sheldon: Then it’s coming from you. You’ve really got to work on your hygiene"
          txt[30] = "You are afraid of insects and women. Ladybugs must render you catatonic"
          txt[31] = "I’m not insane. My mother had me tested"
          txt[32] = "I’m a Hindu. My religion teaches that if we suffer in this life we are rewarded in the next. Three months at the North Pole with Sheldon and I’m reborn as a well-hung billionaire with wings"
          txt[33] = "If a photon is directed through a plane with two slits in it and either slit is observed, it will not go through both slits. If it’s unobserved, it will. However, if it’s observed after it’s left the plane but before it hits its target, it will not have gone through both slits"
          txt[34] = "In difficult moments, fashion is always outrageous"
          txt[35] = "I don’t mind germs, but I’m not a fool. I don’t share utensils. If I see a sneeze coming, I leave the table"
          txt[36] = "Well, it’s official: the Large Hadron Collider is the most awesome thing ever! It’s so awesome, I’m going to pee my pants!"
          txt[37] = "Leonard: I don’t believe this. Raj: He’s drunk. Sheldon: I’m not drunk. I’m just confident"
          txt[38] = "I’m not insane. My mother had me tested"
          txt[39] = "I cry because other people are stupid, and that makes me sad"
          txt[40] = "Biology is the only science in which multiplication means the same thing as division"
          txt[41] = "Bazinga!"
          txt[42] = "Why are you crying? Penny: Because I’m stupid! Sheldon: That’s no reason to cry. One cries because one is sad. For example, I cry because others are stupid, and that makes me sad"
          txt[43] = "I don’t need sleep. I need answers!"
          txt[44] = "You know, I’ve always wanted to be a lion tamer. But since that’s highly unlikely, I’d be thrilled to help you"
          txt[45] = "I’m not insane. My mother had me tested"
          txt[46] = "I’m a Hindu. My religion teaches that if we suffer in this life we are rewarded in the next. Three months at the North Pole with Sheldon and I’m reborn as a well-hung billionaire with wings"
          txt[47] = "I love you, too, Mom. Goodbye. (Hangs up.) She thinks I’m going to die. (Leaves the room.) Well, she’s going to die first"
          txt[48] = "I’m not insane. My mother had me tested"
          txt[49] = "I’ve spent the past three and a half years staring at grease boards full of equations; before that, I spent four years working on my Ph.D. in Theoretical Physics; before that, I was an undergraduate physics major; before that, I was in junior college, and before that, I was in the fifth grade. So if you think that I am not qualified to determine who is or is not a physicist, I suggest you bite me"
          rand=$[$RANDOM % ${#txt[@]}]
          git commit -m "${txt[$rand]}"
      - name: Push commit
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Adds 1 more profile view
        uses: gpuliyar/check-url-action@v1.0.1
        with:
          url: https://gpvc.arturio.dev/${{ secrets.USERNAME }}
          retry-count: 5
